
const constants = {
  GET_ALL_DRIVERS : 'GET_ALL_DRIVERS',
  SET_CURRENT_DRIVER : 'SET_CURRENT_DRIVER',
  EDIT_DRIVER : 'EDIT_DRIVER',
  UPDATE_DRIVER : 'UPDATE_DRIVER',
  CREATE_DRIVER : 'CREATE_DRIVER',
  DELETE_DRIVER : 'DELETE_DRIVER',
  SAVE_NEW_DRIVER : 'SAVE_NEW_DRIVER',
  TOGGLE_MODAL : 'TOGGLE_MODAL',
  AUTH : 'AUTH',
  IS_AUTH: 'IS_AUTH'
}

export { constants } 